In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("data_i/i_ufc_fight_data.xlsx", sheet_name="fight_data")

In [3]:
data.head()

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,R_CLINCH,B_CLINCH,R_GROUND,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date
0,Adrian Yanez,Gustavo Lopez,2,0,41 of 103,23 of 51,0.39,0.45,41 of 103,23 of 51,...,0 of 0,0 of 0,0 of 1,0 of 0,KO/TKO,3,00:27:00,3 Rnd (5-5-5),Chris Tognoni,2021-03-20
1,Trevin Giles,Roman Dolidze,0,0,27 of 57,32 of 67,0.47,0.47,43 of 73,75 of 110,...,4 of 5,3 of 6,8 of 10,1 of 2,Decision - Unanimous,3,05:00:00,3 Rnd (5-5-5),Herb Dean,2021-03-20
2,Tai Tuivasa,Harry Hunsucker,1,0,14 of 18,2 of 6,0.77,0.33,14 of 18,2 of 6,...,0 of 0,0 of 0,5 of 8,0 of 0,KO/TKO,1,00:49:00,3 Rnd (5-5-5),Herb Dean,2021-03-20
3,Cheyanne Buys,Montserrat Conejo,0,0,31 of 65,15 of 41,0.47,0.36,49 of 87,136 of 168,...,2 of 2,0 of 0,3 of 7,0 of 0,Decision - Unanimous,3,05:00:00,3 Rnd (5-5-5),Mark Smith,2021-03-20
4,Marion Reneau,Macy Chiasson,0,0,30 of 63,51 of 138,0.47,0.36,59 of 93,92 of 184,...,5 of 9,13 of 15,0 of 0,2 of 4,Decision - Unanimous,3,05:00:00,3 Rnd (5-5-5),Mark Smith,2021-03-20

In [4]:
# Splitting the 'att' columns
ufc_df = ['R_SIG_STR.', 'B_SIG_STR.', 'R_TOTAL_STR.', 'B_TOTAL_STR.', 'R_TD', 'B_TD', 'R_HEAD', 'B_HEAD', 'R_BODY', 'B_BODY', 'R_LEG', 'B_LEG', 'R_DISTANCE', 'B_DISTANCE', 'R_CLINCH', 'B_CLINCH', 'R_GROUND', 'B_GROUND']
att_columns = ['R_SIG_STR.', 'B_SIG_STR.', 'R_TOTAL_STR.', 'B_TOTAL_STR.', 'R_TD', 'B_TD', 'R_HEAD', 'B_HEAD', 'R_BODY', 'B_BODY', 'R_LEG', 'B_LEG', 'R_DISTANCE', 'B_DISTANCE', 'R_CLINCH', 'B_CLINCH', 'R_GROUND', 'B_GROUND']
for column in att_columns:
    data[column + '_att'] = data[column].str.split(' of ').str[0]
    data[column + '_landed'] = data[column].str.split(' of ').str[1]

# Remove the original columns
data = data.drop(att_columns, axis=1)

data.head(10)

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR_pct,B_SIG_STR_pct,R_TD_pct,B_TD_pct,R_SUB_ATT,B_SUB_ATT,...,B_DISTANCE_att,B_DISTANCE_landed,R_CLINCH_att,R_CLINCH_landed,B_CLINCH_att,B_CLINCH_landed,R_GROUND_att,R_GROUND_landed,B_GROUND_att,B_GROUND_landed
0,Adrian Yanez,Gustavo Lopez,2,0,0.39,0.45,---,0,0,0,...,23,51,0,0,0,0,0,1,0,0
1,Trevin Giles,Roman Dolidze,0,0,0.47,0.47,0.5,0.33,1,2,...,28,59,4,5,3,6,8,10,1,2
2,Tai Tuivasa,Harry Hunsucker,1,0,0.77,0.33,---,---,0,0,...,2,6,0,0,0,0,5,8,0,0
3,Cheyanne Buys,Montserrat Conejo,0,0,0.47,0.36,---,0.8,0,2,...,15,41,2,2,0,0,3,7,0,0
4,Marion Reneau,Macy Chiasson,0,0,0.47,0.36,0.5,1,0,0,...,36,119,5,9,13,15,0,0,2,4
5,Leonardo Santos,Grant Dawson,0,0,0.44,0.54,0.5,0.07,0,0,...,33,68,2,2,9,11,0,0,4,5
6,Song Kenan,Max Griffin,0,1,0.58,0.6,---,0,0,0,...,16,27,0,0,0,0,0,0,1,1
7,Derek Brunson,Kevin Holland,0,0,0.46,0.48,0.5,1,1,0,...,29,64,10,10,5,7,19,40,2,3
8,Montel Jackson,Jesse Strader,2,0,0.57,0.56,---,---,0,0,...,12,22,3,4,0,1,7,10,2,2
9,Bruno Silva,JP Buys,3,0,0.6,0.3,0.5,0,0,1,...,15,53,1,2,2,3,10,16,0,0

In [5]:
data.columns

Index(['R_fighter', 'B_fighter', 'R_KD', 'B_KD', 'R_SIG_STR_pct',
       'B_SIG_STR_pct', 'R_TD_pct', 'B_TD_pct', 'R_SUB_ATT', 'B_SUB_ATT',
       'R_REV', 'B_REV', 'R_CTRL', 'B_CTRL', 'win_by', 'last_round',
       'last_round_time', 'Format', 'Referee', 'date', 'R_SIG_STR._att',
       'R_SIG_STR._landed', 'B_SIG_STR._att', 'B_SIG_STR._landed',
       'R_TOTAL_STR._att', 'R_TOTAL_STR._landed', 'B_TOTAL_STR._att',
       'B_TOTAL_STR._landed', 'R_TD_att', 'R_TD_landed', 'B_TD_att',
       'B_TD_landed', 'R_HEAD_att', 'R_HEAD_landed', 'B_HEAD_att',
       'B_HEAD_landed', 'R_BODY_att', 'R_BODY_landed', 'B_BODY_att',
       'B_BODY_landed', 'R_LEG_att', 'R_LEG_landed', 'B_LEG_att',
       'B_LEG_landed', 'R_DISTANCE_att', 'R_DISTANCE_landed', 'B_DISTANCE_att',
       'B_DISTANCE_landed', 'R_CLINCH_att', 'R_CLINCH_landed', 'B_CLINCH_att',
       'B_CLINCH_landed', 'R_GROUND_att', 'R_GROUND_landed', 'B_GROUND_att',
       'B_GROUND_landed'],
      dtype='object')

In [6]:
data[['R_CTRL', 'B_CTRL', 'last_round_time']].dtypes

R_CTRL             object
B_CTRL             object
last_round_time    object
dtype: object

In [7]:
data['R_CTRL'] = pd.to_timedelta(data['R_CTRL'].astype(str)).dt.total_seconds()

In [8]:
data['R_CTRL']

0        180.0
1       4500.0
2        600.0
3       3840.0
4       8100.0
         ...
6007       NaN
6008       NaN
6009       NaN
6010       NaN
6011       NaN
Name: R_CTRL, Length: 6012, dtype: float64